modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="lavasmelting"
version="1.1"
displayName="Lava Smelting"
authors="Redstoneguy129"
description="Smelt your ores with lava!"
[[dependencies.lavasmelting]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lavasmelting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
